services:
  spark-master:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ./:/app
    networks:
      - big-data-network

  spark-worker:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ./:/app
    networks:
      - big-data-network
    depends_on:
      - spark-master

  data-ingestion:
    build:
      context: .
      dockerfile: ./data_ingestion/Dockerfile
    volumes:
      - ./:/app
    networks:
      - big-data-network
    depends_on:
      - spark-master

  data-preprocessing:
    build:
      context: .
      dockerfile: ./data_preprocessing_cleaning/Dockerfile
    volumes:
      - ./:/app
    networks:
      - big-data-network
    depends_on:
      - spark-master

  ml-module:
    build:
      context: .
      dockerfile: ./ml_module/Dockerfile
    volumes:
      - ./:/app
    networks:
      - big-data-network
    depends_on:
      - spark-master

  sql-analytics:
    build:
      context: .
      dockerfile: ./sql_analytics/Dockerfile
    volumes:
      - ./:/app
    networks:
      - big-data-network
    depends_on:
      - spark-master

networks:
  big-data-network:
    driver: bridge
